workflows:
  ios-build:
    name: RichyVPN iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build archive
        script: |
          cd ios
          xcodebuild -workspace RichyVPN_RN.xcworkspace \
            -scheme RichyVPN_RN \
            -configuration Release \
            -derivedDataPath build \
            -archivePath build/RichyVPN_RN.xcarchive \
            archive
          cd ..
    artifacts:
      - ios/build/RichyVPN_RN.xcarchive
