workflows:
  ios-build:
    name: Build iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: 18
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Install npm
        script: npm install
      - name: Install pods
        script: cd ios && pod install && cd ..
      - name: Build
        script: |
          cd ios
          xcodebuild -scheme RichyVPN_RN -configuration Release -derivedDataPath build archive
          cd ..
    artifacts:
      - ios/build
