workflows:
  ios-build:
    name: RichyVPN iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
        - pull_request
        - tag
    
    scripts:
      - name: Clear cache
        script: |
          watchman watch-del-all || true
          cd $HOME && rm -rf .watchman || true
          cd $HOME && rm -rf .metro || true
      
      - name: Install Node dependencies
        script: npm install
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build iOS Archive
        script: |
          cd ios
          xcodebuild -workspace RichyVPN_RN.xcworkspace \
            -scheme RichyVPN_RN \
            -configuration Release \
            -derivedDataPath build \
            -archivePath build/RichyVPN_RN.xcarchive \
            archive
          cd ..
    
    artifacts:
      - ios/build/RichyVPN_RN.xcarchive
    
    publishing:
      email:
        recipients:
          - user@example.com
